const SUITS=["♦","♠","♥","♣"], RANKS=["2","3","4","5","6","7","8","9","10","J","Q","K","A"], ROUND_CARDS=[7,6,5,4,3,2,1,2,3,4,5,6,7];
const state={mode:"local",room:null,user:{id:crypto.randomUUID(),name:""},players:[],round:0,dealer:0,turn:0,leader:0,trump:null,hands:{},bids:{},won:{},blobs:{},history:{},trick:[],phase:"home",timer:null,time:30};
const $=id=>document.getElementById(id); const screens=["home","lobby","game","results"];
function show(id){screens.forEach(s=>$(s).classList.toggle("active",s===id));state.phase=id}
function shuffle(a){for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function deck(){return shuffle(SUITS.flatMap(s=>RANKS.map((r,i)=>({id:s+r,suit:s,rank:r,value:i+2}))))}
function code(){return Array.from({length:6},()=>"ABCDEFGHJKLMNPQRSTUVWXYZ23456789"[Math.floor(Math.random()*32)]).join("")}
function trumpForRound(r){const i=r%5;return i===4?null:SUITS[i]}
function currentPlayer(){return state.players[state.turn]}
function legalCards(pid){const hand=state.hands[pid]||[];if(state.trick.length){const lead=state.trick[0].card.suit;if(hand.some(c=>c.suit===lead))return hand.filter(c=>c.suit===lead)}return hand}
function handMarkup(pid,legal=[]){return (state.hands[pid]||[]).map(c=>`<button class="playing-card ${legal.some(x=>x.id===c.id)?'legal':'preview'} ${c.suit==='♥'||c.suit==='♦'?'red':''}" ${legal.length?`data-card="${c.id}"`:'disabled'}><span>${c.rank}${c.suit}</span><span>${c.suit}</span></button>`).join("")}
function winner(){const lead=state.trick[0].card.suit;const trumped=state.trump&&state.trick.some(x=>x.card.suit===state.trump);const suit=trumped?state.trump:lead;return state.trick.filter(x=>x.card.suit===suit).sort((a,b)=>b.card.value-a.card.value)[0].pid}
function startTimer(onExpire){clearInterval(state.timer);state.time=30;$("timer").textContent=30;state.timer=setInterval(()=>{state.time--;$("timer").textContent=state.time;if(state.time<=0){clearInterval(state.timer);onExpire()}},1000)}
function startLocal(){state.players=[{id:state.user.id,name:state.user.name||"You",ready:true},{id:"bot1",name:"Mia",ready:true},{id:"bot2",name:"Ben",ready:true}];state.blobs=Object.fromEntries(state.players.map(p=>[p.id,0]));beginRound();}
function beginRound(){state.trump=trumpForRound(state.round);state.dealer=state.round%state.players.length;state.turn=(state.dealer+1)%state.players.length;state.leader=state.turn;state.bids={};state.won=Object.fromEntries(state.players.map(p=>[p.id,0]));state.trick=[];const d=deck(),count=ROUND_CARDS[state.round];state.hands={};state.players.forEach(p=>state.hands[p.id]=d.splice(0,count));show("game");renderGame();beginBidTurn()}
function renderGame(){const count=ROUND_CARDS[state.round];$("roundLabel").textContent=`ROUND ${state.round+1} OF 13 • ${count} CARDS`;$("trumpLabel").textContent=state.trump?`${state.trump} Trump`:`Opening card chooses trump`;$("scoreStrip").innerHTML=state.players.map((p,i)=>`<div class="player-chip ${i===state.turn?'active':''}"><b>${p.name}</b><br>Bid ${state.bids[p.id]??'–'} · Won ${state.won[p.id]??0}<br>😭 ${state.blobs[p.id]||0}</div>`).join("");$("trick").innerHTML=state.trick.map(x=>`<div class="played-card ${x.card.suit==='♥'||x.card.suit==='♦'?'red':''}"><span>${x.card.rank}${x.card.suit}</span><small>${state.players.find(p=>p.id===x.pid).name}</small></div>`).join("")}
function legalBids(){const max=ROUND_CARDS[state.round],made=Object.values(state.bids).reduce((a,b)=>a+b,0),last=Object.keys(state.bids).length===state.players.length-1;return Array.from({length:max+1},(_,i)=>i).filter(v=>!last||made+v!==max)}
function beginBidTurn(){renderGame();const p=currentPlayer();$("turnMessage").textContent=`${p.name} is bidding`;$("handPanel").classList.remove("hidden");$("bidPanel").classList.remove("hidden");$("legalMessage").textContent="Your cards — review your hand before bidding.";$("hand").innerHTML=handMarkup(state.user.id);if(p.id===state.user.id){const bids=legalBids();$("bidChoices").innerHTML=bids.map(v=>`<button class="secondary" data-bid="${v}">${v}</button>`).join("");$("bidRule").textContent=Object.keys(state.bids).length===state.players.length-1?"Final bid cannot make the total equal the cards dealt.":"How many tricks will you win?";document.querySelectorAll("[data-bid]").forEach(b=>b.addEventListener("click",()=>setBid(+b.dataset.bid)));startTimer(()=>setBid(Math.max(...bids)))}else{startTimer(()=>setBid(Math.max(...legalBids())));setTimeout(()=>setBid(Math.floor(Math.random()*(Math.max(...legalBids())+1))),650)}}
function setBid(v){if(state.bids[currentPlayer().id]!=null)return;clearInterval(state.timer);state.bids[currentPlayer().id]=v;if(Object.keys(state.bids).length===state.players.length){state.turn=state.leader;beginPlayTurn()}else{state.turn=(state.turn+1)%state.players.length;beginBidTurn()}}
function beginPlayTurn(){renderGame();$("bidPanel").classList.add("hidden");$("handPanel").classList.remove("hidden");const p=currentPlayer(),legal=legalCards(p.id);$("turnMessage").textContent=`${p.name}'s turn`;if(p.id===state.user.id){const lead=state.trick[0]?.card.suit;const canFollow=lead&&(state.hands[p.id]||[]).some(c=>c.suit===lead);$("legalMessage").textContent=canFollow?`${lead} was led — you must follow suit.`:state.trick.length?"You cannot follow suit — play any card.":"Choose any card to lead.";$("hand").innerHTML=handMarkup(p.id,legal);document.querySelectorAll(".playing-card.legal").forEach(b=>b.addEventListener("click",()=>playCard(b.dataset.card)));startTimer(()=>playCard([...legal].sort((a,b)=>(b.suit===state.trump)-(a.suit===state.trump)||b.value-a.value)[0].id))}else{$("legalMessage").textContent="Waiting for another player…";$("hand").innerHTML="";startTimer(()=>autoPlay(p.id));setTimeout(()=>autoPlay(p.id),700)}}
function autoPlay(pid){if(currentPlayer().id!==pid)return;const legal=legalCards(pid).sort((a,b)=>(b.suit===state.trump)-(a.suit===state.trump)||b.value-a.value);playCard(legal[0].id)}
function playCard(cardId){clearInterval(state.timer);const p=currentPlayer(),legal=legalCards(p.id),card=legal.find(c=>c.id===cardId);if(!card)return;state.hands[p.id]=state.hands[p.id].filter(c=>c.id!==cardId);state.trick.push({pid:p.id,card});if(!state.trump&&state.round%5===4&&state.trick.length===1)state.trump=card.suit;if(state.trick.length===state.players.length){const w=winner();state.won[w]++;renderGame();setTimeout(()=>{state.trick=[];state.turn=state.players.findIndex(p=>p.id===w);state.leader=state.turn;if(state.hands[state.user.id].length===0)endRound();else beginPlayTurn()},900)}else{state.turn=(state.turn+1)%state.players.length;beginPlayTurn()}}
function endRound(){clearInterval(state.timer);const results=state.players.map(p=>{const hit=state.bids[p.id]===state.won[p.id];if(!hit)state.blobs[p.id]=(state.blobs[p.id]||0)+1;(state.history[p.id]??=[]).push(hit?"😁":"😭");return{p,hit}});$("resultBlob").textContent=results.find(r=>r.p.id===state.user.id)?.hit?"😁":"😭";$("resultTitle").textContent=`Round ${state.round+1} complete`;$("resultScores").innerHTML=results.map(r=>`<div class="score-row"><b>${r.p.name}</b><span>Bid ${state.bids[r.p.id]} / Won ${state.won[r.p.id]}</span><span>${r.hit?'😁':'😭'}</span></div>`).join("");show("results")}
$("continueRound").addEventListener("click",()=>{state.round++;if(state.round>=13){const min=Math.min(...Object.values(state.blobs));$("resultTitle").textContent="Game complete";$("resultScores").innerHTML=state.players.map(p=>`<div class="score-row"><b>${p.name}</b><span>${(state.history[p.id]||[]).join(' ')}</span><span>😭 ${state.blobs[p.id]}${state.blobs[p.id]===min?' 🏆':''}</span></div>`).join('');$("continueRound").classList.add("hidden")}else beginRound()});
$("demoGame").addEventListener("click",()=>{state.user.name=$("playerName").value.trim()||"You";startLocal()});
$("createRoom").addEventListener("click",()=>{$("homeStatus").textContent="Firebase must be configured and deployed before online rooms can be created. The included setup guide covers this step."});
$("joinRoom").addEventListener("click",()=>{$("homeStatus").textContent="Online joining activates after the Firebase setup is completed."});
document.querySelectorAll("[data-go]").forEach(b=>b.addEventListener("click",()=>{clearInterval(state.timer);show(b.dataset.go)}));
if("serviceWorker" in navigator)navigator.serviceWorker.register("sw.js");
